cmake_minimum_required(VERSION 3.5 FATAL_ERROR)

# Required inputs (passed via -D): FILE_HEX, FILE_KEY, FILE_MIME,
# EMBED_FILE_PATH, CMAKE_CURRENT_INCLUDE_DIR
file(READ ${FILE_HEX} CONTENT_HEX)
string(SHA256 FILE_KEY_HASH ${FILE_KEY})
configure_file("${CMAKE_CURRENT_INCLUDE_DIR}/xxd.c.in" ${EMBED_FILE_PATH})
